# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=255)),
                ('gid', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('market', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('longname', models.TextField()),
            ],
            options={
                'db_table': 'ss_goods',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ss_img',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ss_user',
            },
        ),
    ]
