# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ss_img',
            },
        ),
    ]
