# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shasha', '0004_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selection',
            field=models.BooleanField(default=True),
        ),
    ]
