# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shasha', '0005_cart_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='selection',
            field=models.IntegerField(default=1),
        ),
    ]
