# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shasha', '0006_auto_20190318_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selectionall',
            field=models.IntegerField(default=1),
        ),
    ]
